### ISSUE TITLE
console.log

### ISSUE THREAD

**Issue by xmnlab** [nesterone/vue-vega#43]
Hey @nesterone !

very nice lib! thanks!

I am playing with vue-vega and it seems awesome!

do you plan to keep maintenance of this library?

it seems each time I use the library it shows (console.log) the spec used. is there a way to silence that?

thanks!

**Comment by nesterone** [comment]
Hi, @xmnlab 

vue-vega is in beta, not much use as I see by dependencies graph ;-)

I'm going to remove those console calls, because looks like I've just forget to clean them

**Comment by xmnlab** [comment]
Thanks @nesterone !

**Comment by xmnlab** [comment]
it seems #44 has already fixed that! thanks!
