### ISSUE TITLE
Update vega and vega-lite

### ISSUE THREAD

**Issue by xmnlab** [nesterone/vue-vega#45]
@nesterone 

Currently there are some functionalities that are not working, such as:

- line with point
- tootip
- datasets

for datasets I could workaround and fix that in my backend before send the spec, but it would be good if it could work without any workaround.

My first guess was update the dependencies #44 

But it seems it is not enough.

Could you provide any information to guide me to fix this issue?

**Comment by nesterone** [comment]
I've created a to-do list for 1.0.0  here #46 

Could we close that one because I've already merged updates in your PR?

**Comment by xmnlab** [comment]
sure! thanks @nesterone !
